define ghost = Character("Ghost", color="#e6e6fa", image="ghost girl")
define lord = Character("Lord", color="#d27d2d", image="lord")
define miss = Character("Young Miss", color="#cbc3e3", image="miss")
define player = Character("[player_name]", color="#e34234")
define unknown = Character("???", color="#fff")
