define friend = Character("Olivia", color="#ffea00")
define lord = Character("Lord", color="#d27d2d", image="lord")
define miss = Character("Young Miss", color="#cbc3e3", image="miss")
define player = Character("[player_name]", color="#fff")
define ghost = Character("Ghost", color="#e6e6fa")
